spring.application.name=notification-service

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=admin
spring.security.user.password=admin

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.retry.multiplier=2.0

# Custom application properties
app.rabbitmq.exchange=notification.exchange
app.rabbitmq.queue=notification.queue
app.rabbitmq.routing-key=notification.routing.key


# Security JWT
app.jwt.secret=NOTIFICATION-SECRET-KEY-256-LONG-ENOUGH-FOR-SECURITY
app.jwt.expiration-milliseconds=86400000

# Suppress Hibernate JDBC Environment logs in console
logging.level.org.hibernate.orm.connections.pooling=WARN
